-- GoldenAge_Config
-- Author: HSbF6HSO3F
-- DateCreated: 2025/7/19 19:03:21
--------------------------------------------------------------
INSERT INTO PlayerItems
    (Domain,                        CivilizationType,               LeaderType,                 Type,                                               Icon,                           Name,                                                       Description,                                                        SortIndex)
VALUES
    ('Players:Expansion2_Players',  'CIVILIZATION_EAGLE_UNION',     'LEADER_LAFFEY_DD459',      'GOLDEN_CIVILIZATION_EAGLE_UNION_CUSTOM_FEATURES', 'ICON_CIVILIZATION_EAGLE_UNION', 'LOC_GOLDEN_CIVILIZATION_EAGLE_UNION_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_EAGLE_UNION_CUSTOM_FEATURES_DESCRIPTION',  999),
    ('Players:Expansion2_Players',  'CIVILIZATION_EAGLE_UNION',     'LEADER_FLASHER_SS249',     'GOLDEN_CIVILIZATION_EAGLE_UNION_CUSTOM_FEATURES', 'ICON_CIVILIZATION_EAGLE_UNION', 'LOC_GOLDEN_CIVILIZATION_EAGLE_UNION_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_EAGLE_UNION_CUSTOM_FEATURES_DESCRIPTION',  999),
    ('Players:Expansion2_Players',  'CIVILIZATION_EAGLE_UNION',     'LEADER_ELDRIDGE_DE173',    'GOLDEN_CIVILIZATION_EAGLE_UNION_CUSTOM_FEATURES', 'ICON_CIVILIZATION_EAGLE_UNION', 'LOC_GOLDEN_CIVILIZATION_EAGLE_UNION_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_EAGLE_UNION_CUSTOM_FEATURES_DESCRIPTION',  999),
    ('Players:Expansion2_Players',  'CIVILIZATION_EAGLE_UNION',     'LEADER_ENTERPRISE_CV6',    'GOLDEN_CIVILIZATION_EAGLE_UNION_CUSTOM_FEATURES', 'ICON_CIVILIZATION_EAGLE_UNION', 'LOC_GOLDEN_CIVILIZATION_EAGLE_UNION_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_EAGLE_UNION_CUSTOM_FEATURES_DESCRIPTION',  999),
    ('Players:Expansion2_Players',  'CIVILIZATION_EAGLE_UNION',     'LEADER_ST_LOUIS_CL49',     'GOLDEN_CIVILIZATION_EAGLE_UNION_CUSTOM_FEATURES', 'ICON_CIVILIZATION_EAGLE_UNION', 'LOC_GOLDEN_CIVILIZATION_EAGLE_UNION_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_EAGLE_UNION_CUSTOM_FEATURES_DESCRIPTION',  999);